name: Build

on: 
  workflow_dispatch:
  push: 
    branches: 
      - 'master'
    paths: 
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '.github/workflows/build.yml'
  pull_request:
    branches: '*'
    paths:
      - '**.cpp'
      - '**.hpp'
      - '**.c'
      - '**.h'
      - '.github/workflows/build.yml'

jobs:
  build-r1:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
        with:
          sdk-version: 26100

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_SYSTEM_VERSION=10.0.26100.0
          cmake -DCMAKE_BUILD_TYPE=Release -DSAMP_VERSION=R1 ../ -A Win32
      
      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Create folder for release
        shell: bash
        run: |
          mkdir dist
          cd dist
          cd ..
          mv ./build/client/Release/sampvoice.asi ./dist/sampvoice.asi
          mv ./setup/files/ ./dist
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sampvoice-R1
          path: dist/*

  build-r3:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
        with:
          sdk-version: 26100

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_SYSTEM_VERSION=10.0.26100.0
          cmake -DCMAKE_BUILD_TYPE=Release -DSAMP_VERSION=R3 ../ -A Win32
      
      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Create folder for release
        shell: bash
        run: |
          mkdir dist
          cd dist
          cd ..
          mv ./build/client/Release/sampvoice.asi ./dist/sampvoice.asi
          mv ./setup/files/ ./dist
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sampvoice-R3
          path: dist/*

  build-dl:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.4
        with:
          sdk-version: 26100

      - name: Generate build files
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_SYSTEM_VERSION=10.0.26100.0
          cmake -DCMAKE_BUILD_TYPE=Release -DSAMP_VERSION=DL ../ -A Win32
      
      - name: Build
        run: |
          cd build
          cmake --build . --config Release

      - name: Create folder for release
        shell: bash
        run: |
          mkdir dist
          cd dist
          cd ..
          mv ./build/client/Release/sampvoice.asi ./dist/sampvoice.asi
          mv ./setup/files/ ./dist
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sampvoice-DL
          path: dist/*